### ISSUE TITLE
Optimize SEO

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/stadt-geschichte-basel.github.io#7]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Use https://jampack.divriots.com/ as in https://github.com/maehr/dhbern.github.io/blob/initialize/.github/workflows/quarto-publish.yml

```
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: .
          to: html

      - name: JamPack
        if: github.event_name != 'pull_request'
        run: |
          npx @divriots/jampack .
```

### What type of pull request would this be?

None
